### ISSUE TITLE
Logo links oben zu klein

### ISSUE THREAD

**Issue by orat** [entropia/gewerbehof-webseite#17]
Das Logo das links oben angezeigt wird, ist so klein dass nichts zu erkennen ist.

**Comment by pascalwittler** [comment]
Plan ist aktuell, das Logo aus dem Header-/Titel-Bereich zu entfernen und stattdessen über der Navigation etwas größer zu zeigen. Das ist allerdings mit dem "Material" Theme nicht super einfach. Außerdem muss für die mobile Navigation noch eine ähnlich prominente Position gefunden werden, die nicht stört.

**Comment by pascalwittler** [comment]
soc hat den erstbesten Ansatz gewählt: edf15a0969fa45c1c3d592c197f9d6a735f2bbd7
