### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by orat** [entropia/gewerbehof-webseite#18]
Ich würde die 3 Punkte 

Deserteursdenkmal
Über uns
Ehemalige

aus der Navigation herausnehmen und in irgendeiner Form abgesetzt unterhalb oder an anderer Stelle auf der Webseite unterbringen. Leider sehe ich auf die schnelle nicht welche Möglichkeiten hier leicht zu haben sind. 

Ich finde das wichtig, damit die zentrale Navigation links "aufgeräumt" aussieht. Die 3 Punkte fallen ein wenig heraus und die Auflistung wirkt dadurch unübersichtlich.

**Comment by orat** [comment]
Ausserdem würde ich eine noch einen Link "Internt" hinzufügen unter dem man unser Wiki und unsere Cloud erreichen kann.

**Comment by soc** [comment]
Ich habe in https://github.com/entropia/gewerbehof-webseite/commit/e858b4b81c7eb4c600cab8e975eb59f2ba9f9aa8 eine Seite "Aktivitäten" erstellt, einige AGs bildhaft aufgelistet und auch das Denkmal dort hin verschoben.

**Comment by orat** [comment]
Bitte Deserteursdenkmal und Ehemalige wieder in die Navigation aufnehmen, vielleicht wie vorgeschlagen abgesetzt.

**Comment by orat** [comment]
ich finde das passt jetzt so.

**Comment by soc** [comment]
Super, danke!
