### ISSUE TITLE
GH-Antrag

### ISSUE THREAD

**Issue by soc** [entropia/gewerbehof-webseite#36]
Antrag von vor zwei Wochen:

> 1. Eine der beiden Webseiten, also https://gewerbehof.test-umgebung.de/ oder https://entropia.github.io/gewerbehof-webseite/ zur neuen Webseite machen.
> 2. Olivers Todo-Liste abarbeiten.

---

Ich würde gerne im Lichte der aktuellen Arbeiten den Antrag etwas erweitern und präzisieren.

Zuerst mal zur Abklärung: @orat, möchtest Du die gewerbehof.test-umgebung-Seite weiterhin vorschlagen, oder bist Du komplett auf die Webseite in diesem Repositorium eingeschwenkt?

Falls letzteres der Fall ist, würde ich folgendes vorschlagen:

---

1. https://entropia.github.io/gewerbehof-webseite wird die neue Webseite des Gewerbehofs.
2. Inhalte:
    - Bei Betrieben/Vereinen mit fehlender Verlinkung nachfragen, ob diese eine Webseite haben, die sie verlinken möchten.
    - Neue Bilder anfertigen
        - Eingang (Torbogen) des Gewerbehofs
        - Hoffläche innen
    - Jährliche Erinnerung an alle Betreiebe und Vereine auf der Mailingliste: Prüfen ob Links und Beschreibungstexte noch aktuell sind.
3. Veranstaltungen und Termine:
    - Neuer TOP jedes Plenums (nach Verlesen des Protokolls): Frage nach aktuellen Veranstaltungen, die auf der Webseite eingetragen werden sollen.
    - Unabhängig davon können neue Termine auch über die intern-Liste oder Mail an das Büro eingereicht werden.
    - Kurzfristig möchten wir Doris zeigen, wie sie Termine auf der Webseite einfügen kann, falls Mitglieder das nicht direkt selbst tun können oder möchten.
    - Mittelfristig ist auch eine Anbindung an die Kalenderfunktion der GH-Cloud möglich.

---

Was haltet Ihr davon?

**Comment by orat** [comment]
Vielen Dank für die Überlegungen und Präzisierung. Meine Erfahrung bezüglich der Zusammenarbeit über das repository und mkdocs ist durchweg positiv. Ich sehe keinen Grund darin die Wordpress-Variante weiterzuverfolgen. Toll, dass sich hier Leute eingebracht haben. Das ist schliesslich das Wesentliche. Am besten wäre es wenn ein so konkreter Antrag von Entropia formal aufs Plenum eingebracht wird. 
Meine ToDo-Liste in der ich vor allem Anmerkungen von Lutz aufgehoben hatte ist jetzt auch obsolet geworden. Darauf brauchen wir eigentlich auch nicht mehr hineinschauen.
