### ISSUE TITLE
Dateinamen auf Deutsch?

### ISSUE THREAD

**Issue by soc** [entropia/gewerbehof-webseite#38]
Zur Zeit sind die Dateinamen der Unterseiten auf Englisch, was sich in der Addresszeile widerspiegelt, z. B. https://entropia.github.io/gewerbehof-webseite/crafts/.

Ich fände es besucherfreundlicher, wenn wir für die Unterseiten ebenfalls Namen auf Deutsch hätten, was denkst Du @orat?

**Comment by orat** [comment]
+1
