### ISSUE TITLE
gh-deploy-Aktion überschreibt CNAME-Datei

### ISSUE THREAD

**Issue by soc** [entropia/gewerbehof-webseite#40]
Nach jeder Seitenaktualisierung muss unter Settings → Pages der Webseitenauftritt neu konfiguriert werden, weil der Build-Prozess im Branch gh-pages (der zur Veröffentlichung genutzt wird) die CNAME-Datei löscht.

Wie kann man das am Besten beheben?

**Comment by jdreichmann** [comment]
Bisschen Kontext, wo kommt denn dieser Branch her und woraus kommt der Branch-Inhalt? in dem .github/workflows steht da nichts, was jetzt erklaert, wie das zeug in den gh-pages branch kommt...

**Comment by jdreichmann** [comment]
https://github.com/entropia/gewerbehof-webseite/tree/main/docs so wie ich das lese ,muesste die CNAME file da rein, ja...
