### ISSUE TITLE
Strukturierung der Rubik Aktuelles

### ISSUE THREAD

**Issue by orat** [entropia/gewerbehof-webseite#42]
Diese Rubik könnten wir mit einer Blogfunktionalität ausstatten, jede Veranstaltung ist dann ein Blog-Artikel der über ein Bild zugänglich gemacht wird. Diese Bilder entsprechend einem Blog sortiert, sodass das oberste der aktuellsten Veranstaltung entspricht. Der Vorteil wäre dass wir so alte Veranstaltungen als Blogbeiträge im System lassen und extern dauerhaft verlinken können. 

Ich hab so was vor vielen Jahren auf verschiedenen Seite schon mal gemacht aber halt mit anderer Technologie:
www.quatrizeps.de
http://friedensdenkmal-karlsruhe.de/

Aktuell experimentiere ich damit das auch mit statisch generierten Webseiten hinzubekommen und verwendet dazu

https://themefisher.com/products/dizer-jekyll

Das ist zwar ein jekyll basiertes System aber vielleicht findest sich was vergleichbares das wir auf der GWH-Webseite leicht integrieren können. Vielleicht läßt sich auch der dizer-theme adaptieren.

**Comment by orat** [comment]
Ganz konkret ist ja jetzt die Veranstaltung mit David Yambio aus der Rubrik Aktuelles zugunsten des Fahrradflohmarksr verschwunden. In der Rubrik Aktivitäten findet sich als erstes noch das Querfunkfest. Das passt für mich nicht. 

"Abgelaufene" Veranstaltungen sollten immer noch sichtbar sein, um einen Eindruck zu bekommen, was in der Vergangenheit alles gelaufen ist und die anstehenden Veranstaltung ganz oben - zeitlichen Sortierung eines Blogs.

**Comment by soc** [comment]
Ja, hatte den Gedanken die individuellen Einträge als individuelle Seiten abzulegen, wie Du schriebst, bzgl. Verlinkbarkeit; und dann eine bzw. zwei Seiten für zukünftige/vergangene Termine.

Querfunkfest ist nur unter Aktivitäten gelandet, weil es nichts anderes zu dem Zeitpunkt gab.

Generell bin ich aber am Überlegen, dass wir die (nächste) anstehende(n) Veranstaltunge(n) auf die Startseite packen sollten, ggf. zu Gunsten von Inhalt, der dann auf "Über Uns" wandern sollte.

**Comment by soc** [comment]
@orat Ich habe mal versucht mit ganz einfachen Mitteln das Problem zu lösen.

Veranstaltungen liegen jetzt einzeln in `news/`, in `aktuelles.md` wird nur noch die "aktuelle" Veranstaltung aus dem `news/`-Ordner includiert. (Die Zeile mit `{% include-markdown ...`.)

Vergangene Veranstaltungen sind nun ebenfalls auf dieser Seite verlinkt.

/cc @ulf-gewerbehof @pascalwittler
